# Generated by Django 4.2.3 on 2024-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('P', 'Packed'), ('D', 'Dispatched'), ('DL', 'Delivered')], default='P', max_length=2),
        ),
    ]
